version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_DB=taskManager_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/insert.sql:/docker-entrypoint-initdb.d/insert.sql

volumes:
  postgres_data:
